version: "3"
services:
  worker_base:
    build: .
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
      - RABBIT_MQ_HOST=rabbit_mq
    command: 'false'

  worker:
    restart: always
    extends:
      service: worker_base
    command: gunicorn --config gunicorn.conf.py wsgi:app
    ports:
    - "5000:5000"
    depends_on:
      - db
      - rabbit_mq
      - migrations

  rabbit_mq:
    image: rabbitmq:3.6
    ports:
    - "5672:5672"
    env_file:
      - env_file

  db:
    image: postgres:10
    restart: on-failure
    env_file:
      - env_file

  migrations:
    extends:
      service: worker_base
    command: flask db upgrade
    restart: on-failure
    depends_on:
      - db
      - rabbit_mq

#
#  example_data_loader:
#    extends:
#      service: base
#    env_file:
#      - env_file
#    command: python load_example_data.py
#    depends_on:
#      - db