"""empty message

Revision ID: 527b2c53b074
Revises: 
Create Date: 2020-11-23 21:20:08.540706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527b2c53b074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Unicode(length=128), nullable=False),
    sa.Column('password', sa.Unicode(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Authority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.Column('city', sa.Unicode(length=128), nullable=True),
    sa.Column('address', sa.Unicode(length=128), nullable=True),
    sa.Column('phone', sa.Unicode(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.Unicode(length=128), nullable=True),
    sa.Column('lastname', sa.Unicode(length=128), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('social_number', sa.Unicode(length=16), nullable=True),
    sa.Column('health_status', sa.Boolean(), nullable=True),
    sa.Column('health_status_change_datetime', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('last_notification_read_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Operator')
    op.drop_table('Customer')
    op.drop_table('Authority')
    op.drop_table('User')
    # ### end Alembic commands ###
